---

- name: Add kubernetes repository.
  yum_repository:
    name: Kubernets
    description: Google kubernetes repository.
    file: kubernetes.repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    repo_gpgcheck: yes
    enabled: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  tags: kubelet

- name: Disable SELinux.
  selinux:
    policy: targeted
    state: permissive
  tags: kubelet

- name: Install kubernetes.
  yum:
    name:
      - kubectl-1.15.4-0
      - kubeadm-1.15.4-0
      - kubelet-1.15.4-0
    disable_excludes: kubernetes
  tags: kubelet

- name: Enable kubelet service.
  systemd:
    name: kubelet
    enabled: yes
    masked: no
  tags: kubelet
