---

- name: Be sure ntp is installed.
  yum:
    name: ntp
    state: present
  tags: prerequisites

- name: Be sure ntpd is running and enabled.
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: prerequisites

- name: Upgrade all packages.
  yum:
    name: '*'
    state: latest
  tags: prerequisites

- name: Check for reboot hint.
  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint
  tags: prerequisites

- name: Correct grub default boot.
  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); grubby --set-default=/boot/vmlinuz-$LAST_KERNEL
  when: reboot_hint.stdout.find("reboot") != -1
  tags: prerequisites

- name: Rebooting.
  command: shutdown -r now "Reboot required for updated kernel"
  async: 1
  poll: 0
  become: yes
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting
  tags: prerequisites

- name: Wait for the reboot.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 390
  when: rebooting or changed
  tags: prerequisites

- name: Set new kubernetes firewall rules.
  copy:
    dest: "/etc/sysctl.d/99-kubernetes.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  tags: prerequisites

- name: Reload syctl.
  shell: sysctl --system
  tags: prerequisites

- name: Disable firewall.
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  tags: prerequisites
  
- name: Disable swap.
  shell: swapoff -a
  tags: prerequisites
